FROM nodesource/jessie:6.3.1

RUN apt-get update && apt-get install -y \
  libzmq3-dev \
  libzmq3

WORKDIR /usr/perception
ADD package.json package.json
ENV NODE_ENV=dev
RUN npm install
RUN npm install -g nodemon mocha
ADD . .
ENTRYPOINT nodemon -L
EXPOSE 3000
